const defaultSites = [
  { url: 'https://google.com', title: 'Google', description: 'Search the web.' },
  { url: 'https://bing.com', title: 'Bing', description: 'Microsoft search engine.' },
  { url: 'https://duckduckgo.com', title: 'DuckDuckGo', description: 'Privacy-focused search.' },
  { url: 'https://yahoo.com', title: 'Yahoo', description: 'News and search.' },
  { url: 'https://youtube.com', title: 'YouTube', description: 'Video platform.' },
  { url: 'https://wikipedia.org', title: 'Wikipedia', description: 'Free encyclopedia.' },
  { url: 'https://stackoverflow.com', title: 'Stack Overflow', description: 'Programming Q&A.' },
  { url: 'https://github.com', title: 'GitHub', description: 'Code hosting and collaboration.' },
  { url: 'https://npmjs.com', title: 'npm', description: 'Package registry for Node.js.' },
  { url: 'https://medium.com', title: 'Medium', description: 'Long-form articles.' },
  { url: 'https://dev.to', title: 'Dev.to', description: 'Developer articles and tutorials.' },
  { url: 'https://reddit.com', title: 'Reddit', description: 'Community discussions.' },
  { url: 'https://poki.com', title: 'Poki', description: 'Online games.' },
  { url: 'https://friv.com', title: 'Friv', description: 'Casual online games.' },
  { url: 'https://itch.io', title: 'Itch.io', description: 'Indie games marketplace.' },
  { url: 'https://cnn.com', title: 'CNN', description: 'News.' },
  { url: 'https://bbc.com', title: 'BBC', description: 'News.' },
  { url: 'https://nytimes.com', title: 'The New York Times', description: 'News.' },
  { url: 'https://instagram.com', title: 'Instagram', description: 'Photo and video sharing.' },
  { url: 'https://twitter.com', title: 'X (Twitter)', description: 'Social network.' },
  { url: 'https://facebook.com', title: 'Facebook', description: 'Social network.' },
  { url: 'https://tiktok.com', title: 'TikTok', description: 'Short video platform.' },
  { url: 'https://linkedin.com', title: 'LinkedIn', description: 'Professional network.' },
  { url: 'https://pinterest.com', title: 'Pinterest', description: 'Ideas and images.' },
  { url: 'https://quora.com', title: 'Quora', description: 'Questions and answers.' },
  { url: 'https://imdb.com', title: 'IMDB', description: 'Movie database.' },
  { url: 'https://twitch.tv', title: 'Twitch', description: 'Live streaming platform.' },
  { url: 'https://spotify.com', title: 'Spotify', description: 'Music streaming.' },
  { url: 'https://soundcloud.com', title: 'SoundCloud', description: 'Audio sharing.' },
  { url: 'https://vimeo.com', title: 'Vimeo', description: 'Video hosting for creators.' },
  { url: 'https://amazon.com', title: 'Amazon', description: 'Online shopping.' },
  { url: 'https://ebay.com', title: 'eBay', description: 'Marketplace auction site.' },
  { url: 'https://etsy.com', title: 'Etsy', description: 'Handmade & vintage marketplace.' },
  { url: 'https://aliexpress.com', title: 'AliExpress', description: 'Global online marketplace.' },
  { url: 'https://walmart.com', title: 'Walmart', description: 'Retail store.' },
  { url: 'https://airbnb.com', title: 'Airbnb', description: 'Short-term lodging marketplace.' },
  { url: 'https://booking.com', title: 'Booking.com', description: 'Travel reservations.' },
  { url: 'https://craigslist.org', title: 'Craigslist', description: 'Local classifieds.' },
  { url: 'https://indeed.com', title: 'Indeed', description: 'Job search.' },
  { url: 'https://glassdoor.com', title: 'Glassdoor', description: 'Company reviews & jobs.' },
  { url: 'https://monster.com', title: 'Monster', description: 'Job listings.' },
  { url: 'https://zoom.us', title: 'Zoom', description: 'Video conferencing.' },
  { url: 'https://dropbox.com', title: 'Dropbox', description: 'File storage and sharing.' },
  { url: 'https://drive.google.com', title: 'Google Drive', description: 'Cloud storage.' },
  { url: 'https://notion.so', title: 'Notion', description: 'Notes and docs workspace.' },
  { url: 'https://trello.com', title: 'Trello', description: 'Kanban project boards.' },
  { url: 'https://asana.com', title: 'Asana', description: 'Project management.' },
  { url: 'https://jira.com', title: 'Atlassian Jira', description: 'Issue tracking & project management.' },
  { url: 'https://heroku.com', title: 'Heroku', description: 'App hosting platform.' },
  { url: 'https://netlify.com', title: 'Netlify', description: 'Web hosting and CI.' },
  { url: 'https://vercel.com', title: 'Vercel', description: 'Frontend deployment platform.' },
  { url: 'https://digitalocean.com', title: 'DigitalOcean', description: 'Cloud infrastructure.' },
  { url: 'https://aws.amazon.com', title: 'AWS', description: 'Amazon Web Services.' },
  { url: 'https://azure.microsoft.com', title: 'Microsoft Azure', description: 'Cloud platform.' },
  { url: 'https://cloud.google.com', title: 'Google Cloud', description: 'Cloud services.' },
  { url: 'https://firebase.google.com', title: 'Firebase', description: 'App backend services.' },
  { url: 'https://github.com/explore', title: 'GitHub Explore', description: 'Discover projects.' },
  { url: 'https://gitlab.com', title: 'GitLab', description: 'DevOps platform.' },
  { url: 'https://bitbucket.org', title: 'Bitbucket', description: 'Code hosting.' },
  { url: 'https://codesandbox.io', title: 'CodeSandbox', description: 'Online code editor.' },
  { url: 'https://stackblitz.com', title: 'StackBlitz', description: 'Online dev environment.' },
  { url: 'https://replit.com', title: 'Replit', description: 'Online IDE and hosting.' },
  { url: 'https://jsfiddle.net', title: 'JSFiddle', description: 'Frontend playground.' },
  { url: 'https://codeshare.io', title: 'CodeShare', description: 'Share code quickly.' },
  { url: 'https://pastebin.com', title: 'Pastebin', description: 'Share text and code snippets.' },
  { url: 'https://unsplash.com', title: 'Unsplash', description: 'Free stock photos.' },
  { url: 'https://pexels.com', title: 'Pexels', description: 'Free photos & videos.' },
  { url: 'https://pixabay.com', title: 'Pixabay', description: 'Free images and videos.' },
  { url: 'https://maps.google.com', title: 'Google Maps', description: 'Maps and directions.' },
  { url: 'https://www.openstreetmap.org', title: 'OpenStreetMap', description: 'Open map data.' },
  { url: 'https://finance.yahoo.com', title: 'Yahoo Finance', description: 'Markets and finance news.' },
  { url: 'https://bloomberg.com', title: 'Bloomberg', description: 'Business and markets news.' },
  { url: 'https://coinbase.com', title: 'Coinbase', description: 'Cryptocurrency exchange.' },
  { url: 'https://coindesk.com', title: 'CoinDesk', description: 'Crypto news.' },
  { url: 'https://hackernews.com', title: 'Hacker News', description: 'Tech news and discussion.' },
  { url: 'https://arxiv.org', title: 'arXiv', description: 'Preprint research papers.' },
  { url: 'https://pubmed.ncbi.nlm.nih.gov', title: 'PubMed', description: 'Medical literature.' },
  { url: 'https://coursera.org', title: 'Coursera', description: 'Online courses.' },
  { url: 'https://udemy.com', title: 'Udemy', description: 'Online learning marketplace.' },
  { url: 'https://edx.org', title: 'edX', description: 'University courses online.' },
  { url: 'https://khanacademy.org', title: 'Khan Academy', description: 'Free learning resources.' },
  { url: 'https://codecademy.com', title: 'Codecademy', description: 'Learn to code.' },
  { url: 'https://freecodecamp.org', title: 'freeCodeCamp', description: 'Coding curriculum and articles.' },
  { url: 'https://theverge.com', title: 'The Verge', description: 'Tech news and culture.' },
  { url: 'https://techcrunch.com', title: 'TechCrunch', description: 'Startup and tech news.' },
  { url: 'https://wired.com', title: 'Wired', description: 'Technology and culture.' },
  { url: 'https://arstechnica.com', title: 'Ars Technica', description: 'Technology news.' },
  { url: 'https://engadget.com', title: 'Engadget', description: 'Gadget news.' },
  { url: 'https://newgrounds.com', title: 'Newgrounds', description: 'Flash and web games/art.' },
  { url: 'https://kongregate.com', title: 'Kongregate', description: 'Online games portal.' },
  { url: 'https://miniclip.com', title: 'Miniclip', description: 'Online casual games.' },
  { url: 'https://armorgames.com', title: 'Armor Games', description: 'Browser games.' },
  { url: 'https://addictinggames.com', title: 'Addicting Games', description: 'Free online games.' },
  { url: 'https://metacritic.com', title: 'Metacritic', description: 'Reviews aggregation for games/movies.' },
  { url: 'https://rottentomatoes.com', title: 'Rotten Tomatoes', description: 'Movie reviews.' },
  { url: 'https://boxofficemojo.com', title: 'Box Office Mojo', description: 'Box office statistics.' },
  { url: 'https://yelp.com', title: 'Yelp', description: 'Local business reviews.' },
  { url: 'https://tripadvisor.com', title: 'Tripadvisor', description: 'Travel reviews and booking.' },
  { url: 'https://healthline.com', title: 'Healthline', description: 'Health information.' },
  { url: 'https://webmd.com', title: 'WebMD', description: 'Medical information.' },
  { url: 'https://dictionary.com', title: 'Dictionary.com', description: 'Definitions and word reference.' },
  { url: 'https://thesaurus.com', title: 'Thesaurus.com', description: 'Synonyms and antonyms.' },
  { url: 'https://dictionary.cambridge.org', title: 'Cambridge Dictionary', description: 'Language reference.' },
  { url: 'https://oxforddictionaries.com', title: 'Oxford Dictionaries', description: 'Language reference.' },
  { url: 'https://opensource.org', title: 'Open Source Initiative', description: 'Open source licenses and projects.' },
  { url: 'https://opensource.com', title: 'OpenSource.com', description: 'Stories about open source.' },
];

export default defaultSites;
