export interface GameMeta {
  id: string;
  title: string;
  developer: string;
  type: "3D" | "2D Top-Down" | "2D Platformer" | "Retro Emulator" | "Arcade" | "Sports" | "Puzzle" | "Strategy" | "Discovery";
  genre: string[];
  description: string;
  bannerUrl: string;
  iconUrl: string;
  releaseDate: string;
  price: string;
  route: string; // The URL to launch the game
}

const premiumGames: GameMeta[] = [
  {
    id: "cyber_pulse",
    title: "Cyber Pulse 2099",
    developer: "Xakteir Studios",
    type: "Arcade",
    genre: ["Action", "Sci-Fi", "Shooter", "Arcade"],
    description: "Pilot your high-tech starfighter against endless swarms of rogue mechs. Upgrade weapons, unleash EMP blasts, and dominate the galaxy.",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    iconUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=cyberpulse",
    releaseDate: "2026",
    price: "Free",
    route: "/game"
  },
  {
    id: "code_arena",
    title: "Code Arena",
    developer: "Xakteir Studios",
    type: "Arcade",
    genre: ["Coding", "Multiplayer", "Competitive"],
    description: "Race against other developers to solve algorithmic challenges in real-time. The first to pass all test cases wins the battle.",
    bannerUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80",
    iconUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=codearena",
    releaseDate: "2026",
    price: "Free",
    route: "/games/code-arena"
  },
  {
    id: "xaksports",
    title: "XakSports",
    developer: "Xakteir Studios",
    type: "3D",
    genre: ["Sports", "Multiplayer", "Physics"],
    description: "The ultimate 3D local and online multiplayer sports arena. Play 1v1 splitscreen or 4-player chaos.",
    bannerUrl: "https://images.unsplash.com/photo-1518605368461-1e1e11407e3c?auto=format&fit=crop&w=1200&q=80",
    iconUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=xaksports",
    releaseDate: "2026",
    price: "Free",
    route: "/xaksports"
  },
  {
    id: "xakarena",
    title: "XakArena",
    developer: "Xakteir Studios",
    type: "3D",
    genre: ["Shooter", "Action", "FPS"],
    description: "Fast-paced 3D arena shooter powered by WebGL. Lock and load.",
    bannerUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1200&q=80",
    iconUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=xakarena",
    releaseDate: "Coming Soon",
    price: "Free",
    route: "/xakarena"
  },
  {
    id: "retro_engine",
    title: "Retro Engine",
    developer: "Open Source",
    type: "Retro Emulator",
    genre: ["Emulator", "Classic"],
    description: "Play your favorite classic console ROMs directly in the browser using WebAssembly. Drag, drop, and play.",
    bannerUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
    iconUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=retro",
    releaseDate: "Beta",
    price: "Free",
    route: "/games/retro"
  },
  {
    id: "neon_drift",
    title: "Neon Drift",
    developer: "Xakteir Studios",
    type: "2D Top-Down",
    genre: ["Racing", "Arcade"],
    description: "Top-down cyber-racing with intense drift mechanics.",
    bannerUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=1200&q=80",
    iconUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=neondrift",
    releaseDate: "2026",
    price: "$4.99",
    route: "/games/play/neon_drift"
  },
  {
    id: "pixel_knight",
    title: "Pixel Knight",
    developer: "IndieForge",
    type: "2D Platformer",
    genre: ["Adventure", "Platformer"],
    description: "A classic 2D platforming adventure through dangerous dungeons.",
    bannerUrl: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=1200&q=80",
    iconUrl: "https://api.dicebear.com/7.x/shapes/svg?seed=pixelknight",
    releaseDate: "2026",
    price: "Free",
    route: "/games/play/pixel_knight"
  }
];

const legacyGamesData = [
  { id: 'aim', name: 'Aim Trainer', type: 'Arcade' },
  { id: 'balance', name: 'Balance Board', type: 'Puzzle' },
  { id: 'basketball', name: 'Basketball Shoot', type: 'Sports' },
  { id: 'breaker', name: 'Brick Breaker', type: 'Arcade' },
  { id: 'bubble', name: 'Bubble Shooter', type: 'Puzzle' },
  { id: 'clickSpeed', name: 'Click Speed', type: 'Arcade' },
  { id: 'clicker', name: 'Idle Clicker', type: 'Strategy' },
  { id: 'colorMatch', name: 'Color Match', type: 'Puzzle' },
  { id: 'connectFour', name: 'Connect Four', type: 'Strategy' },
  { id: 'dodge', name: 'Dodge Objects', type: 'Arcade' },
  { id: 'drawing', name: 'Drawing Canvas', type: 'Discovery' },
  { id: 'fishing', name: 'Fishing Game', type: 'Arcade' },
  { id: 'flappy', name: 'Flappy Bird', type: 'Arcade' },
  { id: 'football3D', name: 'Football 3D', type: '3D' },
  { id: 'frogger', name: 'Frogger Cross', type: 'Arcade' },
  { id: 'golf', name: 'Mini Golf', type: 'Sports' },
  { id: 'gravity', name: 'Gravity Flip', type: 'Arcade' },
  { id: 'invaders', name: 'Space Invaders', type: 'Arcade' },
  { id: 'jump', name: 'Infinite Jump', type: 'Arcade' },
  { id: 'knife', name: 'Knife Hit', type: 'Arcade' },
  { id: 'match3', name: 'Match 3', type: 'Puzzle' },
  { id: 'math', name: 'Math Quiz', type: 'Puzzle' },
  { id: 'maze', name: 'Maze Solver', type: 'Puzzle' },
  { id: 'memory', name: 'Memory Cards', type: 'Puzzle' },
  { id: 'minesweeper', name: 'Minesweeper', type: 'Strategy' },
  { id: 'paint', name: 'Paint & Draw', type: 'Discovery' },
  { id: 'parking', name: 'Car Parking', type: 'Puzzle' },
  { id: 'pinball', name: 'Pinball Classic', type: 'Arcade' },
  { id: 'plinko', name: 'Plinko Drop', type: 'Arcade' },
  { id: 'pong', name: 'Classic Pong', type: 'Arcade' },
  { id: 'rps', name: 'Rock Paper Scissors', type: 'Strategy' },
  { id: 'reaction', name: 'Reaction Time', type: 'Arcade' },
  { id: 'sequence', name: 'Memory Sequence', type: 'Puzzle' },
  { id: 'snake', name: 'Snake Game', type: 'Arcade' },
  { id: 'spinWheel', name: 'Spin The Wheel', type: 'Discovery' },
  { id: 'stack', name: 'Tower Stacker', type: 'Arcade' },
  { id: 'sudoku', name: 'Sudoku Classic', type: 'Puzzle' },
  { id: 'tictactoe', name: 'Tic Tac Toe', type: 'Strategy' },
  { id: 'towerDefense', name: 'Tower Defense', type: 'Strategy' },
  { id: 'trivia', name: 'Trivia Quiz', type: 'Discovery' },
  { id: 'tunnel3D', name: 'Tunnel 3D', type: '3D' },
  { id: 'twoZeroFourEight', name: '2048 Puzzle', type: 'Puzzle' },
  { id: 'typing', name: 'Typing Test', type: 'Discovery' },
  { id: 'whack', name: 'Whack-a-Mole', type: 'Arcade' },
  { id: 'word', name: 'Word Search', type: 'Puzzle' },
  { id: 'xbr', name: 'XBR Arena', type: '3D' },
  { id: 'blockDrop', name: 'Block Drop', type: 'Arcade' },
  { id: 'mazeMuncher', name: 'Maze Muncher', type: 'Arcade' },
  { id: 'wordGuess', name: 'Word Guess', type: 'Puzzle' },
  { id: 'spaceRocks', name: 'Space Rocks', type: 'Arcade' },
  { id: 'rhythmTap', name: 'Rhythm Tap', type: 'Arcade' }
];

const legacyGames: GameMeta[] = legacyGamesData.map(g => ({
  id: g.id,
  title: g.name,
  developer: "xakteir",
  type: g.type as any,
  genre: [g.type, "Casual"],
  description: `Classic ${g.name} experience available right in your browser.`,
  bannerUrl: `https://picsum.photos/seed/${g.id}/1200/800`,
  iconUrl: `https://api.dicebear.com/7.x/shapes/svg?seed=${g.id}`,
  releaseDate: "Classic",
  price: "Free",
  route: `/games/play/${g.id}`
}));

export const GAMES_DB: GameMeta[] = [...premiumGames, ...legacyGames,
  { id: 'aeroDrift', name: 'Aero Drift', type: 'Action' },
  { id: 'aeroDrift2', name: 'Aero Drift2', type: 'Sports' },
  { id: 'aeroMatch', name: 'Aero Match', type: 'Action' },
  { id: 'aeroMatch2', name: 'Aero Match2', type: 'Arcade' },
  { id: 'aeroSurfer', name: 'Aero Surfer', type: 'Puzzle' },
  { id: 'aimTrainer', name: 'Aim Trainer', type: 'Sports' },
  { id: 'aquaBlaster', name: 'Aqua Blaster', type: 'Sports' },
  { id: 'aquaBlaster2', name: 'Aqua Blaster2', type: 'Puzzle' },
  { id: 'aquaDrop', name: 'Aqua Drop', type: 'Action' },
  { id: 'aquaDrop2', name: 'Aqua Drop2', type: 'Sports' },
  { id: 'aquaMatch', name: 'Aqua Match', type: 'Puzzle' },
  { id: 'astroDash', name: 'Astro Dash', type: 'Puzzle' },
  { id: 'astroDash2', name: 'Astro Dash2', type: 'Arcade' },
  { id: 'astroDrop', name: 'Astro Drop', type: 'Arcade' },
  { id: 'astroLink', name: 'Astro Link', type: 'Puzzle' },
  { id: 'astroSpin', name: 'Astro Spin', type: 'Strategy' },
  { id: 'astroSpin2', name: 'Astro Spin2', type: 'Arcade' },
  { id: 'balanceBoard', name: 'Balance Board', type: 'Action' },
  { id: 'brickBreaker', name: 'Brick Breaker', type: 'Arcade' },
  { id: 'bubbleShooter', name: 'Bubble Shooter', type: 'Strategy' },
  { id: 'carParking', name: 'Car Parking', type: 'Puzzle' },
  { id: 'chronoClash', name: 'Chrono Clash', type: 'Sports' },
  { id: 'chronoClash2', name: 'Chrono Clash2', type: 'Action' },
  { id: 'chronoDefender', name: 'Chrono Defender', type: 'Action' },
  { id: 'chronoDefender2', name: 'Chrono Defender2', type: 'Sports' },
  { id: 'chronoQuest', name: 'Chrono Quest', type: 'Sports' },
  { id: 'cosmicBlaster', name: 'Cosmic Blaster', type: 'Sports' },
  { id: 'cosmicBlaster2', name: 'Cosmic Blaster2', type: 'Sports' },
  { id: 'cosmicBounce', name: 'Cosmic Bounce', type: 'Strategy' },
  { id: 'cosmicDefender', name: 'Cosmic Defender', type: 'Puzzle' },
  { id: 'cosmicDrop', name: 'Cosmic Drop', type: 'Strategy' },
  { id: 'cosmicDrop2', name: 'Cosmic Drop2', type: 'Strategy' },
  { id: 'cosmicMatch', name: 'Cosmic Match', type: 'Strategy' },
  { id: 'crazyLink', name: 'Crazy Link', type: 'Arcade' },
  { id: 'crazyNinja', name: 'Crazy Ninja', type: 'Arcade' },
  { id: 'crazyNinja2', name: 'Crazy Ninja2', type: 'Puzzle' },
  { id: 'crazyQuest', name: 'Crazy Quest', type: 'Action' },
  { id: 'crazyQuest2', name: 'Crazy Quest2', type: 'Arcade' },
  { id: 'crazySpin', name: 'Crazy Spin', type: 'Strategy' },
  { id: 'crystalDrop', name: 'Crystal Drop', type: 'Puzzle' },
  { id: 'crystalNinja', name: 'Crystal Ninja', type: 'Strategy' },
  { id: 'crystalRacer', name: 'Crystal Racer', type: 'Action' },
  { id: 'crystalRacer2', name: 'Crystal Racer2', type: 'Puzzle' },
  { id: 'crystalStrike', name: 'Crystal Strike', type: 'Arcade' },
  { id: 'crystalStrike2', name: 'Crystal Strike2', type: 'Sports' },
  { id: 'cyberClash', name: 'Cyber Clash', type: 'Sports' },
  { id: 'cyberDash', name: 'Cyber Dash', type: 'Action' },
  { id: 'cyberDash2', name: 'Cyber Dash2', type: 'Action' },
  { id: 'cyberPuzzle', name: 'Cyber Puzzle', type: 'Puzzle' },
  { id: 'cyberSpin', name: 'Cyber Spin', type: 'Arcade' },
  { id: 'cyberSpin2', name: 'Cyber Spin2', type: 'Sports' },
  { id: 'cyberSpin3', name: 'Cyber Spin3', type: 'Action' },
  { id: 'dodgeObjects', name: 'Dodge Objects', type: 'Arcade' },
  { id: 'drawingCanvas', name: 'Drawing Canvas', type: 'Sports' },
  { id: 'electroDash', name: 'Electro Dash', type: 'Sports' },
  { id: 'electroRacer', name: 'Electro Racer', type: 'Arcade' },
  { id: 'electroRacer2', name: 'Electro Racer2', type: 'Action' },
  { id: 'electroStrike', name: 'Electro Strike', type: 'Sports' },
  { id: 'electroStrike2', name: 'Electro Strike2', type: 'Sports' },
  { id: 'epicClash', name: 'Epic Clash', type: 'Action' },
  { id: 'epicDrift', name: 'Epic Drift', type: 'Sports' },
  { id: 'epicDrift2', name: 'Epic Drift2', type: 'Puzzle' },
  { id: 'epicMatch', name: 'Epic Match', type: 'Puzzle' },
  { id: 'epicMatch2', name: 'Epic Match2', type: 'Action' },
  { id: 'epicShooter', name: 'Epic Shooter', type: 'Strategy' },
  { id: 'eternalRunner', name: 'Eternal Runner', type: 'Strategy' },
  { id: 'finalBoss', name: 'Final Boss', type: 'Action' },
  { id: 'fishingGame', name: 'Fishing Game', type: 'Arcade' },
  { id: 'flappyBird', name: 'Flappy Bird', type: 'Action' },
  { id: 'galaxyBlaster', name: 'Galaxy Blaster', type: 'Arcade' },
  { id: 'game2048', name: 'Game2048', type: 'Puzzle' },
  { id: 'grandStrategy', name: 'Grand Strategy', type: 'Strategy' },
  { id: 'gravityFlip', name: 'Gravity Flip', type: 'Arcade' },
  { id: 'hyperGlider', name: 'Hyper Glider', type: 'Strategy' },
  { id: 'hyperGlider2', name: 'Hyper Glider2', type: 'Action' },
  { id: 'hyperKnight', name: 'Hyper Knight', type: 'Puzzle' },
  { id: 'hyperKnight2', name: 'Hyper Knight2', type: 'Action' },
  { id: 'hyperLink', name: 'Hyper Link', type: 'Action' },
  { id: 'hyperRacer', name: 'Hyper Racer', type: 'Strategy' },
  { id: 'idleClicker', name: 'Idle Clicker', type: 'Puzzle' },
  { id: 'infiniteJump', name: 'Infinite Jump', type: 'Strategy' },
  { id: 'infinityMatch', name: 'Infinity Match', type: 'Puzzle' },
  { id: 'ironBlaster', name: 'Iron Blaster', type: 'Action' },
  { id: 'ironForce', name: 'Iron Force', type: 'Strategy' },
  { id: 'ironRunner', name: 'Iron Runner', type: 'Action' },
  { id: 'ironRunner2', name: 'Iron Runner2', type: 'Sports' },
  { id: 'ironSurfer', name: 'Iron Surfer', type: 'Strategy' },
  { id: 'ironSurfer2', name: 'Iron Surfer2', type: 'Strategy' },
  { id: 'knifeHit', name: 'Knife Hit', type: 'Action' },
  { id: 'legendQuest', name: 'Legend Quest', type: 'Strategy' },
  { id: 'lunarDefender', name: 'Lunar Defender', type: 'Arcade' },
  { id: 'lunarRacer', name: 'Lunar Racer', type: 'Action' },
  { id: 'lunarRunner', name: 'Lunar Runner', type: 'Puzzle' },
  { id: 'lunarRunner2', name: 'Lunar Runner2', type: 'Action' },
  { id: 'lunarSurfer', name: 'Lunar Surfer', type: 'Strategy' },
  { id: 'lunarSurfer2', name: 'Lunar Surfer2', type: 'Puzzle' },
  { id: 'magicClash', name: 'Magic Clash', type: 'Puzzle' },
  { id: 'magicClash2', name: 'Magic Clash2', type: 'Sports' },
  { id: 'magicDefender', name: 'Magic Defender', type: 'Strategy' },
  { id: 'magicDefender2', name: 'Magic Defender2', type: 'Strategy' },
  { id: 'magicKnight', name: 'Magic Knight', type: 'Puzzle' },
  { id: 'magicSpin', name: 'Magic Spin', type: 'Arcade' },
  { id: 'masterArcade', name: 'Master Arcade', type: 'Arcade' },
  { id: 'mathQuiz', name: 'Math Quiz', type: 'Strategy' },
  { id: 'mazeSolver', name: 'Maze Solver', type: 'Strategy' },
  { id: 'megaBounce', name: 'Mega Bounce', type: 'Puzzle' },
  { id: 'megaGlider', name: 'Mega Glider', type: 'Strategy' },
  { id: 'megaGlider2', name: 'Mega Glider2', type: 'Strategy' },
  { id: 'megaKnight', name: 'Mega Knight', type: 'Sports' },
  { id: 'megaKnight2', name: 'Mega Knight2', type: 'Sports' },
  { id: 'megaSports', name: 'Mega Sports', type: 'Action' },
  { id: 'megaSurfer', name: 'Mega Surfer', type: 'Strategy' },
  { id: 'memoryCards', name: 'Memory Cards', type: 'Arcade' },
  { id: 'memorySequence', name: 'Memory Sequence', type: 'Action' },
  { id: 'miniGolf', name: 'Mini Golf', type: 'Sports' },
  { id: 'mysticRunner', name: 'Mystic Runner', type: 'Strategy' },
  { id: 'mysticRunner2', name: 'Mystic Runner2', type: 'Action' },
  { id: 'mysticSurfer', name: 'Mystic Surfer', type: 'Puzzle' },
  { id: 'mysticSurfer2', name: 'Mystic Surfer2', type: 'Sports' },
  { id: 'mysticWizard', name: 'Mystic Wizard', type: 'Action' },
  { id: 'mythicDefender', name: 'Mythic Defender', type: 'Puzzle' },
  { id: 'neonBounce', name: 'Neon Bounce', type: 'Arcade' },
  { id: 'neonBounce2', name: 'Neon Bounce2', type: 'Arcade' },
  { id: 'neonDash', name: 'Neon Dash', type: 'Action' },
  { id: 'neonDrift', name: 'Neon Drift', type: 'Strategy' },
  { id: 'neonKnight', name: 'Neon Knight', type: 'Arcade' },
  { id: 'neonRunner', name: 'Neon Runner', type: 'Puzzle' },
  { id: 'neonShooter', name: 'Neon Shooter', type: 'Strategy' },
  { id: 'neonShooter2', name: 'Neon Shooter2', type: 'Sports' },
  { id: 'paintDraw', name: 'Paint Draw', type: 'Strategy' },
  { id: 'pixelBlaster', name: 'Pixel Blaster', type: 'Sports' },
  { id: 'pixelClash', name: 'Pixel Clash', type: 'Puzzle' },
  { id: 'pixelClash2', name: 'Pixel Clash2', type: 'Action' },
  { id: 'pixelDefender', name: 'Pixel Defender', type: 'Strategy' },
  { id: 'pixelDefender2', name: 'Pixel Defender2', type: 'Action' },
  { id: 'pixelDrift', name: 'Pixel Drift', type: 'Action' },
  { id: 'pixelKnight', name: 'Pixel Knight', type: 'Action' },
  { id: 'pixelQuest', name: 'Pixel Quest', type: 'Sports' },
  { id: 'pyroForce', name: 'Pyro Force', type: 'Sports' },
  { id: 'pyroForce2', name: 'Pyro Force2', type: 'Strategy' },
  { id: 'pyroLink', name: 'Pyro Link', type: 'Action' },
  { id: 'pyroLink2', name: 'Pyro Link2', type: 'Arcade' },
  { id: 'pyroStrike', name: 'Pyro Strike', type: 'Action' },
  { id: 'quantumBounce', name: 'Quantum Bounce', type: 'Puzzle' },
  { id: 'quantumDrift', name: 'Quantum Drift', type: 'Arcade' },
  { id: 'quantumDrift2', name: 'Quantum Drift2', type: 'Sports' },
  { id: 'quantumMatch', name: 'Quantum Match', type: 'Sports' },
  { id: 'quantumMatch2', name: 'Quantum Match2', type: 'Puzzle' },
  { id: 'quantumShooter', name: 'Quantum Shooter', type: 'Arcade' },
  { id: 'quantumStrike', name: 'Quantum Strike', type: 'Action' },
  { id: 'reactionTime', name: 'Reaction Time', type: 'Action' },
  { id: 'retroBlaster', name: 'Retro Blaster', type: 'Sports' },
  { id: 'retroEngine', name: 'Retro Engine', type: 'Action' },
  { id: 'retroForce', name: 'Retro Force', type: 'Action' },
  { id: 'retroForce2', name: 'Retro Force2', type: 'Strategy' },
  { id: 'retroLink', name: 'Retro Link', type: 'Puzzle' },
  { id: 'retroLink2', name: 'Retro Link2', type: 'Puzzle' },
  { id: 'retroRacer', name: 'Retro Racer', type: 'Puzzle' },
  { id: 'rockPaperScissors', name: 'Rock Paper Scissors', type: 'Action' },
  { id: 'shadowBlaster', name: 'Shadow Blaster', type: 'Sports' },
  { id: 'shadowForce', name: 'Shadow Force', type: 'Strategy' },
  { id: 'shadowForce2', name: 'Shadow Force2', type: 'Action' },
  { id: 'shadowGlider', name: 'Shadow Glider', type: 'Puzzle' },
  { id: 'shadowLink', name: 'Shadow Link', type: 'Sports' },
  { id: 'shadowLink2', name: 'Shadow Link2', type: 'Arcade' },
  { id: 'shadowNinja', name: 'Shadow Ninja', type: 'Arcade' },
  { id: 'solarBounce', name: 'Solar Bounce', type: 'Puzzle' },
  { id: 'solarBounce2', name: 'Solar Bounce2', type: 'Strategy' },
  { id: 'solarGlider', name: 'Solar Glider', type: 'Arcade' },
  { id: 'solarNinja', name: 'Solar Ninja', type: 'Arcade' },
  { id: 'solarShooter', name: 'Solar Shooter', type: 'Arcade' },
  { id: 'solarShooter2', name: 'Solar Shooter2', type: 'Action' },
  { id: 'sonicDrop', name: 'Sonic Drop', type: 'Action' },
  { id: 'sonicGlider2', name: 'Sonic Glider2', type: 'Puzzle' },
  { id: 'sonicGlider3', name: 'Sonic Glider3', type: 'Sports' },
  { id: 'sonicKnight', name: 'Sonic Knight', type: 'Sports' },
  { id: 'sonicKnight2', name: 'Sonic Knight2', type: 'Action' },
  { id: 'spaceInvaders', name: 'Space Invaders', type: 'Action' },
  { id: 'steelBounce', name: 'Steel Bounce', type: 'Puzzle' },
  { id: 'steelBounce2', name: 'Steel Bounce2', type: 'Action' },
  { id: 'steelNinja', name: 'Steel Ninja', type: 'Strategy' },
  { id: 'steelShooter', name: 'Steel Shooter', type: 'Strategy' },
  { id: 'steelShooter2', name: 'Steel Shooter2', type: 'Arcade' },
  { id: 'superBlaster', name: 'Super Blaster', type: 'Arcade' },
  { id: 'superBlaster2', name: 'Super Blaster2', type: 'Arcade' },
  { id: 'superDrop', name: 'Super Drop', type: 'Strategy' },
  { id: 'superDrop2', name: 'Super Drop2', type: 'Strategy' },
  { id: 'superKnight', name: 'Super Knight', type: 'Strategy' },
  { id: 'superRunner', name: 'Super Runner', type: 'Sports' },
  { id: 'terraBuilder', name: 'Terra Builder', type: 'Arcade' },
  { id: 'terraNinja', name: 'Terra Ninja', type: 'Strategy' },
  { id: 'terraNinja2', name: 'Terra Ninja2', type: 'Puzzle' },
  { id: 'terraQuest', name: 'Terra Quest', type: 'Strategy' },
  { id: 'terraQuest2', name: 'Terra Quest2', type: 'Action' },
  { id: 'ticTacToe', name: 'Tic Tac Toe', type: 'Arcade' },
  { id: 'towerStacker', name: 'Tower Stacker', type: 'Puzzle' },
  { id: 'triviaQuiz', name: 'Trivia Quiz', type: 'Sports' },
  { id: 'turboForce', name: 'Turbo Force', type: 'Sports' },
  { id: 'turboMatch', name: 'Turbo Match', type: 'Arcade' },
  { id: 'turboNinja', name: 'Turbo Ninja', type: 'Sports' },
  { id: 'turboNinja2', name: 'Turbo Ninja2', type: 'Strategy' },
  { id: 'turboQuest', name: 'Turbo Quest', type: 'Strategy' },
  { id: 'turboQuest2', name: 'Turbo Quest2', type: 'Strategy' },
  { id: 'turboSurfer', name: 'Turbo Surfer', type: 'Arcade' },
  { id: 'typingTest', name: 'Typing Test', type: 'Strategy' },
  { id: 'ultimatePuzzle', name: 'Ultimate Puzzle', type: 'Arcade' },
  { id: 'ultraDefender', name: 'Ultra Defender', type: 'Sports' },
  { id: 'ultraDrift', name: 'Ultra Drift', type: 'Sports' },
  { id: 'ultraRacer', name: 'Ultra Racer', type: 'Arcade' },
  { id: 'ultraRacer2', name: 'Ultra Racer2', type: 'Sports' },
  { id: 'ultraStrike', name: 'Ultra Strike', type: 'Strategy' },
  { id: 'ultraStrike2', name: 'Ultra Strike2', type: 'Arcade' },
  { id: 'voidDash', name: 'Void Dash', type: 'Strategy' },
  { id: 'voidDash2', name: 'Void Dash2', type: 'Strategy' },
  { id: 'voidShooter', name: 'Void Shooter', type: 'Action' },
  { id: 'voidSpin', name: 'Void Spin', type: 'Action' },
  { id: 'voidSpin2', name: 'Void Spin2', type: 'Strategy' },
  { id: 'whackAMole', name: 'Whack A Mole', type: 'Strategy' },
  { id: 'wordSearch', name: 'Word Search', type: 'Sports' },
  { id: 'xakArena', name: 'Xak Arena', type: 'Strategy' },
  { id: 'xakSports', name: 'Xak Sports', type: 'Arcade' },
  { id: 'xBRArena', name: 'X B R Arena', type: 'Puzzle' }
];
