import { NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';

type Message = {
  role: 'user' | 'model';
  content: string;
  senderName?: string;
};

export async function POST(request: Request) {
  try {
    const { messages, title }: { messages: Message[]; title: string } = await request.json();

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    const usableWidth = pageWidth - margin * 2;
    let y = margin;

    // Header Background
    doc.setFillColor(10, 5, 25);
    doc.rect(0, 0, pageWidth, 32, 'F');

    // Title & Logo
    doc.setTextColor(147, 51, 234); // Violet accent
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('XAK AI', margin, 16);

    doc.setTextColor(220, 220, 240);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Transcript: ${title || 'Untitled Session'}`, margin, 24);

    const exportDate = new Date().toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
    const dateWidth = doc.getTextWidth(exportDate);
    doc.setTextColor(150, 150, 170);
    doc.text(exportDate, pageWidth - margin - dateWidth, 20);

    y = 42;

    messages.forEach((msg, idx) => {
      const isUser = msg.role === 'user';
      const label = isUser ? `[USER] ${msg.senderName || 'You'}` : '✦ [XAK AI]';
      const textColor = isUser ? [180, 180, 255] : [135, 230, 180];

      // Strip non-printable ASCII characters for clean jsPDF rendering
      const cleanContent = (msg.content || '')
        .replace(/[^\x00-\x7F]/g, '')
        .trim();

      if (!cleanContent) return;

      const lines = doc.splitTextToSize(cleanContent, usableWidth - 10);
      const blockHeight = 10 + lines.length * 4.5 + 6;

      if (y + blockHeight > pageHeight - margin - 15) {
        doc.addPage();
        y = margin;
      }

      // Sender Label
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...(textColor as [number, number, number]));
      doc.text(label, margin, y);
      y += 5;

      // Message Box
      const bgColor = isUser ? [22, 18, 45] : [12, 28, 22];
      doc.setFillColor(...(bgColor as [number, number, number]));
      doc.roundedRect(margin, y - 2, usableWidth, lines.length * 4.5 + 6, 2, 2, 'F');

      // Message Text
      doc.setFontSize(8.5);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(230, 230, 240);
      doc.text(lines, margin + 5, y + 3);
      y += lines.length * 4.5 + 12;
    });

    // Page Numbering Footer
    const totalPages = (doc.internal as any).getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(7.5);
      doc.setTextColor(120, 120, 140);
      doc.text('Generated by Xak AI — Xakteir Ecosystem', margin, pageHeight - 8);
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 20, pageHeight - 8);
    }

    const pdfBuffer = doc.output('arraybuffer');

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="xak-ai-${Date.now()}.pdf"`,
      },
    });
  } catch (err: any) {
    console.error('PDF export error:', err);
    return NextResponse.json({ error: 'Failed to generate PDF: ' + err.message }, { status: 500 });
  }
}
