import { NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';

type Message = {
  role: 'user' | 'model';
  content: string;
  senderName?: string;
};

export async function POST(request: Request) {
  try {
    const { messages, title }: { messages: Message[]; title: string } = await request.json();

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const usableWidth = pageWidth - margin * 2;
    let y = margin;

    // Header
    doc.setFillColor(10, 5, 30);
    doc.rect(0, 0, pageWidth, 35, 'F');
    doc.setTextColor(160, 100, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('XAK AI', margin, 18);
    doc.setTextColor(200, 200, 200);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Chat Export: ${title || 'Untitled Session'}`, margin, 27);

    const exportDate = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
    const dateWidth = doc.getTextWidth(exportDate);
    doc.text(exportDate, pageWidth - margin - dateWidth, 22);

    y = 50;

    messages.forEach((msg) => {
      const isUser = msg.role === 'user';
      const label = isUser ? (msg.senderName || 'You') : '✦ Xak AI';
      const textColor = isUser ? [200, 200, 255] : [160, 255, 200];

      // Check if we need a new page
      const lines = doc.splitTextToSize(msg.content, usableWidth - 10);
      const blockHeight = 12 + lines.length * 5 + 6;
      if (y + blockHeight > pageHeight - margin) {
        doc.addPage();
        y = margin;
      }

      // Label
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...(textColor as [number, number, number]));
      doc.text(label, margin, y);
      y += 6;

      // Background box
      const bgColor = isUser ? [25, 20, 50] : [15, 30, 25];
      doc.setFillColor(...(bgColor as [number, number, number]));
      doc.roundedRect(margin, y - 3, usableWidth, lines.length * 5 + 8, 2, 2, 'F');

      // Message text
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(220, 220, 220);
      doc.text(lines, margin + 5, y + 3);
      y += lines.length * 5 + 16;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 120);
    doc.text('Generated by Xak AI — Xakteir', margin, pageHeight - 10);

    const pdfBuffer = doc.output('arraybuffer');

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="xak-ai-chat-${Date.now()}.pdf"`,
      },
    });
  } catch (err: any) {
    console.error('PDF export error:', err);
    return NextResponse.json({ error: 'Failed to generate PDF: ' + err.message }, { status: 500 });
  }
}
