// Generated by eve. Do not edit by hand.

import * as module_0 from "../../agent/agent.ts";
import * as module_1 from "../../agent/tools/createDocument.ts";
import * as module_2 from "../../agent/tools/manageDNS.ts";
import * as module_3 from "../../agent/tools/sendNotification.ts";
import * as module_4 from "../../agent/tools/updateUserBalance.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "tools/createDocument.ts": module_1,
                  "tools/manageDNS.ts": module_2,
                  "tools/sendNotification.ts": module_3,
                  "tools/updateUserBalance.ts": module_4
                })
            })
    })
});

export default moduleMap;
