/**
 * ============================================================================
 * VOLTRA OS ENTERPRISE KERNEL - EXECUTABLE AND LINKABLE FORMAT (ELF)
 * ============================================================================
 * 
 * DESCRIPTION:
 * For VoltraOS to run User Space applications (like the QML Desktop Daemon),
 * it must know how to parse standard ELF binary files generated by compilers 
 * like GCC and Clang.
 * 
 * CORE CONCEPTS:
 * 1. ELF Header: Contains the magic number (0x7F 'E' 'L' 'F'), machine type 
 *    (x86 or x86_64), and the entry point address.
 * 2. Program Headers (Segments): Tells the OS how to map the file into 
 *    Virtual Memory. Usually includes a .text segment (Executable Code), 
 *    a .data segment (Initialized variables), and a .bss segment (Uninitialized
 *    variables that the OS must zero out).
 * 3. Ring 3 Transition: Once the binary is mapped into memory using `vmm_map_page`,
 *    the kernel builds a hardware stack frame and executes an `iret` instruction 
 *    to intentionally drop privileges from Ring 0 (Kernel) to Ring 3 (User Space).
 * ============================================================================
 */

#ifndef ELF_H
#define ELF_H

#include <stdint.h>
#include <stdbool.h>
#include "vfs.h"
#include "task.h"

// ELF Magic Numbers
#define ELFMAG0 0x7F
#define ELFMAG1 'E'
#define ELFMAG2 'L'
#define ELFMAG3 'F'

// ELF Classes
#define ELFCLASS32 1
#define ELFCLASS64 2

// Program Header Types
#define PT_NULL    0
#define PT_LOAD    1
#define PT_DYNAMIC 2

// Program Header Flags
#define PF_X 1 // Executable
#define PF_W 2 // Writable
#define PF_R 4 // Readable

// ----------------------------------------------------------------------------
// STRUCTURES (Supporting both 32-bit and 64-bit binaries)
// ----------------------------------------------------------------------------

typedef struct {
    uint8_t  e_ident[16];
    uint16_t e_type;
    uint16_t e_machine;
    uint32_t e_version;
    uint32_t e_entry;
    uint32_t e_phoff;
    uint32_t e_shoff;
    uint32_t e_flags;
    uint16_t e_ehsize;
    uint16_t e_phentsize;
    uint16_t e_phnum;
    uint16_t e_shentsize;
    uint16_t e_shnum;
    uint16_t e_shstrndx;
} elf32_ehdr_t;

typedef struct {
    uint32_t p_type;
    uint32_t p_offset;
    uint32_t p_vaddr;
    uint32_t p_paddr;
    uint32_t p_filesz;
    uint32_t p_memsz;
    uint32_t p_flags;
    uint32_t p_align;
} elf32_phdr_t;

// ----------------------------------------------------------------------------
// PUBLIC API
// ----------------------------------------------------------------------------

/**
 * @brief Loads an ELF binary from the Virtual File System (VFS) and prepares 
 * it for execution as a new Process.
 * 
 * @param path The path to the executable (e.g., "/bin/desktop_daemon").
 * @return Pointer to the newly created Task Control Block (TCB), or NULL on failure.
 */
task_struct_t* elf_load_executable(const char* path);

/**
 * @brief Executes the final architecture-specific context switch to drop 
 * into Ring 3 User Mode and start the application.
 */
void switch_to_user_mode(uint32_t entry_point, uint32_t user_stack);

#endif // ELF_H
