"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Terminal, BarChart3, PackagePlus, Wallet, FileText, 
  Settings, LogOut, Code2, Users, ArrowRight, CheckCircle2,
  Gamepad2, Zap
} from "lucide-react";

export default function CreatorPlatform() {
  // Mock state to toggle between the application page and the dashboard
  const [isApprovedCreator, setIsApprovedCreator] = useState(false);
  const [isApplying, setIsApplying] = useState(false);

  const handleApply = () => {
    setIsApplying(true);
    // Simulate an API call / application process
    setTimeout(() => {
      setIsApplying(false);
      setIsApprovedCreator(true);
    }, 2000);
  };

  if (!isApprovedCreator) {
    return (
      <div className="min-h-screen bg-black text-white flex flex-col font-sans selection:bg-orange-500/30 overflow-hidden relative">
        {/* Background Gradients */}
        <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] bg-orange-600/20 blur-[120px] rounded-full pointer-events-none" />
        <div className="absolute bottom-[-20%] right-[-10%] w-[50%] h-[50%] bg-purple-600/20 blur-[120px] rounded-full pointer-events-none" />

        <nav className="p-8 flex items-center justify-between relative z-10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-orange-500 to-red-600 flex items-center justify-center">
              <Code2 className="w-6 h-6 text-white" />
            </div>
            <span className="text-xl font-bold tracking-widest uppercase">Xakteir Studio</span>
          </div>
        </nav>

        <main className="flex-1 flex flex-col items-center justify-center px-4 relative z-10">
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-3xl w-full text-center"
          >
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-500/10 border border-orange-500/20 text-orange-400 text-sm font-medium mb-8">
              <Zap className="w-4 h-4" /> Creator Program Beta
            </div>
            
            <h1 className="text-5xl md:text-7xl font-black tracking-tighter mb-6 bg-clip-text text-transparent bg-gradient-to-br from-white via-white to-white/50">
              Build the Next <br/> Great Arena.
            </h1>
            
            <p className="text-xl text-white/60 mb-12 max-w-2xl mx-auto leading-relaxed">
              Join the Xakarena Creator Program. Use our custom engine or the Unity SDK to build, publish, and monetize your own game modes directly on our network.
            </p>

            <motion.div
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
            >
              <button 
                onClick={handleApply}
                disabled={isApplying}
                className="relative group bg-white text-black px-8 py-4 rounded-full font-bold text-lg flex items-center gap-3 mx-auto overflow-hidden transition-all shadow-[0_0_40px_rgba(249,115,22,0.3)] hover:shadow-[0_0_60px_rgba(249,115,22,0.5)] disabled:opacity-70 disabled:cursor-not-allowed"
              >
                <div className="absolute inset-0 bg-gradient-to-r from-orange-400 to-red-500 opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                <span className="relative z-10 group-hover:text-white transition-colors">
                  {isApplying ? "Submitting Application..." : "Apply for Access"}
                </span>
                {!isApplying && <ArrowRight className="relative z-10 w-5 h-5 group-hover:text-white transition-colors" />}
              </button>
            </motion.div>
          </motion.div>

          <div className="mt-24 grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl w-full">
            <FeatureCard 
              icon={<Terminal className="w-6 h-6 text-orange-400" />}
              title="Powerful Tooling"
              desc="Build logic using XakScript or bring your own C# code via our Unity SDK integration."
            />
            <FeatureCard 
              icon={<Users className="w-6 h-6 text-purple-400" />}
              title="Instant Audience"
              desc="Publish directly to the Xakarena hub. Your games are instantly playable by thousands."
            />
            <FeatureCard 
              icon={<Wallet className="w-6 h-6 text-green-400" />}
              title="Monetization"
              desc="Keep 70% of the revenue generated by your games through battle passes and cosmetics."
            />
          </div>
        </main>
      </div>
    );
  }

  // --- Creator Dashboard View ---
  return (
    <div className="flex h-screen bg-[#0a0a0a] text-white font-sans overflow-hidden selection:bg-orange-500/30">
      {/* Sidebar */}
      <aside className="w-64 border-r border-white/10 bg-black/50 backdrop-blur-xl flex flex-col">
        <div className="p-6 flex items-center gap-3 border-b border-white/5">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-orange-500 to-red-600 flex items-center justify-center">
            <Code2 className="w-5 h-5 text-white" />
          </div>
          <span className="font-bold tracking-wide">Xakteir Studio</span>
        </div>

        <div className="flex-1 py-6 px-4 space-y-1">
          <SidebarItem active icon={<BarChart3 />} label="Dashboard" />
          <SidebarItem icon={<Gamepad2 />} label="My Games" />
          <SidebarItem icon={<Wallet />} label="Payouts" badge="New" />
          <SidebarItem icon={<FileText />} label="Documentation" />
        </div>

        <div className="p-4 border-t border-white/10">
          <SidebarItem icon={<Settings />} label="Settings" />
          <button 
            onClick={() => setIsApprovedCreator(false)}
            className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-white/50 hover:text-white hover:bg-white/5 transition-colors text-sm font-medium mt-1"
          >
            <LogOut className="w-5 h-5" />
            Sign Out
          </button>
        </div>
      </aside>

      {/* Main Dashboard Content */}
      <main className="flex-1 overflow-y-auto bg-gradient-to-br from-[#0a0a0a] to-[#111]">
        <div className="p-10 max-w-6xl mx-auto">
          <header className="flex items-center justify-between mb-10">
            <div>
              <h1 className="text-3xl font-bold tracking-tight mb-1">Welcome back, Creator.</h1>
              <p className="text-white/50">Here's what's happening with your games today.</p>
            </div>
            <button className="bg-white text-black px-5 py-2.5 rounded-lg font-semibold flex items-center gap-2 hover:bg-white/90 transition-colors shadow-lg">
              <PackagePlus className="w-5 h-5" />
              New Game
            </button>
          </header>

          {/* Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
            <StatCard title="Total Active Players" value="12,402" trend="+14%" isPositive={true} />
            <StatCard title="Revenue (30d)" value="$4,250.00" trend="+5%" isPositive={true} />
            <StatCard title="Avg. Playtime" value="45m" trend="-2%" isPositive={false} />
          </div>

          {/* Published Games List */}
          <h2 className="text-xl font-bold mb-6">Published Games</h2>
          <div className="space-y-4">
            <GameRow 
              title="Neon Drift Racing" 
              status="Active" 
              players="8,021" 
              revenue="$3,100" 
              thumbnail="from-blue-500 to-purple-600"
            />
            <GameRow 
              title="Zombie Survival X" 
              status="Needs Update" 
              players="4,381" 
              revenue="$1,150" 
              thumbnail="from-green-500 to-emerald-700"
            />
          </div>
        </div>
      </main>
    </div>
  );
}

// --- Helper Components ---

function FeatureCard({ icon, title, desc }: { icon: React.ReactNode, title: string, desc: string }) {
  return (
    <div className="p-6 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-sm text-left hover:bg-white/10 transition-colors">
      <div className="w-12 h-12 rounded-xl bg-white/5 flex items-center justify-center mb-4 border border-white/5">
        {icon}
      </div>
      <h3 className="text-lg font-bold mb-2">{title}</h3>
      <p className="text-white/50 text-sm leading-relaxed">{desc}</p>
    </div>
  );
}

function SidebarItem({ icon, label, active, badge }: { icon: React.ReactNode, label: string, active?: boolean, badge?: string }) {
  return (
    <button className={`w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all ${
      active 
        ? "bg-gradient-to-r from-orange-500/20 to-red-500/10 text-orange-400 font-semibold border border-orange-500/20" 
        : "text-white/60 hover:text-white hover:bg-white/5 font-medium"
    }`}>
      <div className="flex items-center gap-3">
        {React.cloneElement(icon as React.ReactElement<any>, { className: "w-5 h-5" })}
        <span className="text-sm">{label}</span>
      </div>
      {badge && (
        <span className="px-2 py-0.5 rounded-md bg-orange-500/20 text-orange-400 text-[10px] uppercase font-bold tracking-wider">
          {badge}
        </span>
      )}
    </button>
  );
}

function StatCard({ title, value, trend, isPositive }: { title: string, value: string, trend: string, isPositive: boolean }) {
  return (
    <div className="p-6 rounded-2xl bg-white/5 border border-white/10 flex flex-col justify-between">
      <span className="text-white/50 text-sm font-medium mb-4">{title}</span>
      <div className="flex items-end justify-between">
        <span className="text-3xl font-bold">{value}</span>
        <span className={`text-sm font-semibold px-2 py-1 rounded-md ${isPositive ? "bg-green-500/20 text-green-400" : "bg-red-500/20 text-red-400"}`}>
          {trend}
        </span>
      </div>
    </div>
  );
}

function GameRow({ title, status, players, revenue, thumbnail }: { title: string, status: string, players: string, revenue: string, thumbnail: string }) {
  return (
    <div className="flex items-center justify-between p-4 rounded-xl bg-white/5 border border-white/5 hover:bg-white/10 transition-colors group cursor-pointer">
      <div className="flex items-center gap-4">
        <div className={`w-16 h-12 rounded-lg bg-gradient-to-br ${thumbnail} shadow-inner`} />
        <div>
          <h4 className="font-bold">{title}</h4>
          <div className="flex items-center gap-2 mt-1">
            <span className="flex items-center gap-1 text-xs text-white/50">
              <span className={`w-1.5 h-1.5 rounded-full ${status === 'Active' ? 'bg-green-400' : 'bg-yellow-400'}`} />
              {status}
            </span>
          </div>
        </div>
      </div>

      <div className="flex items-center gap-12 pr-4">
        <div className="flex flex-col items-end">
          <span className="text-white/50 text-xs font-medium uppercase tracking-wider mb-1">Players</span>
          <span className="font-semibold text-sm">{players}</span>
        </div>
        <div className="flex flex-col items-end">
          <span className="text-white/50 text-xs font-medium uppercase tracking-wider mb-1">Revenue</span>
          <span className="font-semibold text-sm text-green-400">{revenue}</span>
        </div>
        <Settings className="w-5 h-5 text-white/20 group-hover:text-white/80 transition-colors" />
      </div>
    </div>
  );
}
