'use client';

import { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Gamepad2, X, Play, RefreshCw, Code2, Eye, Share2, Sparkles,
  Maximize2, Save, CheckCircle2, Trophy, Flame
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { useToast } from '@/hooks/use-toast';
import { useUser, useFirestore } from '@/firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';

const DEFAULT_SNAKE_CODE = `<!DOCTYPE html>
<html>
<head>
  <style>
    body { background: #05030d; color: #fff; text-align: center; font-family: sans-serif; margin: 0; padding: 20px; }
    canvas { background: #0e0b20; border: 2px solid #7c3aed; border-radius: 12px; box-shadow: 0 0 20px rgba(124,58,237,0.3); }
    h1 { color: #a78bfa; margin-bottom: 5px; font-size: 20px; }
    p { color: #94a3b8; font-size: 12px; }
  </style>
</head>
<body>
  <h1>CYBER SNAKE 2088</h1>
  <p>Use Arrow Keys to Navigate. Eat Neon Orbs!</p>
  <canvas id="gc" width="400" height="400"></canvas>
  <script>
    const canvas = document.getElementById('gc');
    const ctx = canvas.getContext('2d');
    let px=10, py=10, gs=20, tc=20, ax=15, ay=15, xv=0, yv=0, trail=[], tail=5, score=0;

    window.onload = () => {
      document.addEventListener('keydown', keyPush);
      setInterval(game, 1000/15);
    };

    function game() {
      px += xv; py += yv;
      if (px < 0) px = tc - 1; if (px >= tc) px = 0;
      if (py < 0) py = tc - 1; if (py >= tc) py = 0;

      ctx.fillStyle = '#0e0b20';
      ctx.fillRect(0, 0, canvas.width, canvas.height);

      ctx.fillStyle = '#a78bfa';
      for (let i = 0; i < trail.length; i++) {
        ctx.fillRect(trail[i].x*gs, trail[i].y*gs, gs-2, gs-2);
        if (trail[i].x === px && trail[i].y === py && (xv !== 0 || yv !== 0)) tail = 5;
      }
      trail.push({x:px, y:py});
      while (trail.length > tail) trail.shift();

      if (ax === px && ay === py) {
        tail++; score += 10;
        ax = Math.floor(Math.random()*tc);
        ay = Math.floor(Math.random()*tc);
      }

      ctx.fillStyle = '#f43f5e';
      ctx.beginPath();
      ctx.arc(ax*gs+gs/2, ay*gs+gs/2, gs/2-2, 0, Math.PI*2);
      ctx.fill();

      ctx.fillStyle = '#fff';
      ctx.font = '12px sans-serif';
      ctx.fillText('Score: ' + score, 10, 20);
    }

    function keyPush(e) {
      switch(e.keyCode) {
        case 37: if(xv!==1){xv=-1;yv=0;} break;
        case 38: if(yv!==1){xv=0;yv=-1;} break;
        case 39: if(xv!==-1){xv=1;yv=0;} break;
        case 40: if(yv!==-1){xv=0;yv=1;} break;
      }
    }
  </script>
</body>
</html>`;

interface GameGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  initialCode?: string;
  gameTitle?: string;
}

export function GameGeneratorModal({
  isOpen,
  onClose,
  initialCode = DEFAULT_SNAKE_CODE,
  gameTitle = "Cyber AI Game Prototype"
}: GameGeneratorModalProps) {
  const [code, setCode] = useState(initialCode);
  const [title, setTitle] = useState(gameTitle);
  const [activeTab, setActiveTab] = useState<'play' | 'code'>('play');
  const [iframeKey, setIframeKey] = useState(0);
  const [isPublishing, setIsPublishing] = useState(false);

  const { user } = useUser();
  const firestore = useFirestore();
  const { toast } = useToast();

  const handleRestart = () => {
    setIframeKey(k => k + 1);
  };

  const handleSaveToGames = async () => {
    if (!firestore || !user) {
      toast({ title: "Sign in to save games", description: "Log in to add this to your collection." });
      return;
    }
    setIsPublishing(true);
    try {
      await addDoc(collection(firestore, "publishedProjects"), {
        name: title,
        description: "Playable game generated by Xak AI",
        code: code,
        authorId: user.uid,
        authorName: user.displayName || "Anonymous Creator",
        createdAt: serverTimestamp(),
        likes: 1,
        category: "AI Games",
      });
      toast({ title: "🎮 Published to Games Library!", description: `"${title}" is now playable in Games.` });
      setIsPublishing(false);
    } catch (e) {
      toast({ variant: "destructive", title: "Failed to save game" });
      setIsPublishing(false);
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[100] bg-black/85 backdrop-blur-2xl flex items-center justify-center p-4 lg:p-8"
        >
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.95, opacity: 0 }}
            className="w-full max-w-4xl h-[85vh] bg-[#070512] border border-white/10 rounded-3xl shadow-2xl flex flex-col overflow-hidden"
          >
            {/* Header */}
            <div className="h-14 bg-white/5 border-b border-white/10 px-5 flex items-center justify-between shrink-0 gap-3">
              <div className="flex items-center gap-3">
                <div className="w-9 h-9 rounded-xl bg-purple-500/15 border border-purple-500/30 flex items-center justify-center text-purple-400">
                  <Gamepad2 className="w-5 h-5" />
                </div>
                <div>
                  <input
                    type="text"
                    value={title}
                    onChange={e => setTitle(e.target.value)}
                    className="bg-transparent border-0 font-black text-sm text-white focus:outline-none focus:ring-0 uppercase tracking-tight"
                  />
                  <p className="text-[10px] text-emerald-400 font-bold uppercase tracking-wider flex items-center gap-1">
                    <Sparkles className="w-3 h-3" /> Live Playable Sandbox
                  </p>
                </div>
              </div>

              {/* Center switcher */}
              <div className="flex items-center gap-1 p-1 bg-black/40 border border-white/10 rounded-xl">
                <button
                  onClick={() => setActiveTab('play')}
                  className={cn(
                    'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-black uppercase tracking-wider transition-all',
                    activeTab === 'play' ? 'bg-primary text-white shadow-lg shadow-primary/20' : 'text-white/40 hover:text-white'
                  )}
                >
                  <Play className="w-3.5 h-3.5" /> Play
                </button>
                <button
                  onClick={() => setActiveTab('code')}
                  className={cn(
                    'flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-black uppercase tracking-wider transition-all',
                    activeTab === 'code' ? 'bg-primary text-white shadow-lg shadow-primary/20' : 'text-white/40 hover:text-white'
                  )}
                >
                  <Code2 className="w-3.5 h-3.5" /> Code
                </button>
              </div>

              {/* Actions */}
              <div className="flex items-center gap-2">
                <button
                  onClick={handleRestart}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 text-white/70 text-xs font-bold transition-all"
                >
                  <RefreshCw className="w-3.5 h-3.5" /> Restart
                </button>
                <button
                  onClick={handleSaveToGames}
                  disabled={isPublishing}
                  className="flex items-center gap-1.5 px-4 py-1.5 rounded-xl bg-emerald-500 hover:bg-emerald-400 text-black font-black text-xs uppercase tracking-wider transition-all shadow-lg shadow-emerald-500/20"
                >
                  <Save className="w-3.5 h-3.5" /> {isPublishing ? "Saving..." : "Save Game"}
                </button>
                <button
                  onClick={onClose}
                  className="w-8 h-8 flex items-center justify-center rounded-xl hover:bg-white/10 text-white/40 hover:text-white transition-all"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Content Area */}
            <div className="flex-1 relative bg-black">
              {activeTab === 'play' ? (
                <iframe
                  key={iframeKey}
                  srcDoc={code}
                  className="w-full h-full border-0 bg-[#05030d]"
                  sandbox="allow-scripts allow-modals allow-same-origin"
                  title="Game Preview"
                />
              ) : (
                <textarea
                  value={code}
                  onChange={e => setCode(e.target.value)}
                  className="w-full h-full p-6 bg-zinc-950 font-mono text-xs text-sky-400 leading-relaxed focus:outline-none resize-none border-0"
                  spellCheck={false}
                />
              )}
            </div>

            {/* Footer */}
            <div className="h-10 bg-black/60 border-t border-white/5 px-4 flex items-center justify-between shrink-0 text-[10px] text-white/40">
              <span className="flex items-center gap-1">
                <Flame className="w-3.5 h-3.5 text-amber-400" /> Powered by Xak AI Game Studio
              </span>
              <span>Click Save Game to publish to /games library</span>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
